language: ruby
cache: bundler
sudo: true
addons:
  postgresql: '9.3'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - npm install
# Please don't add extra test commands here unless they are Travis only -- Jenkins will run this script too
script: bash ./runtests.sh
