default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: money-to-prisoners_development

test: &test
  <<: *default
  database: money-to-prisoners_test

production:
  <<: *default
  database: money-to-prisoners_production
  username: money-to-prisoners
  password: <%= ENV['MONEY-TO-PRISONERS_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
