# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed6d55b35e7a1f85af4428f217e6ae28cf7a69bcc603c8a4334f12c490308005b7838494a1b512d406f25781f4348a76e647c05a49dc1e774cbae6ac20df0a51

test:
  secret_key_base: 506c154bfbcc55a700cbd4f680fb5a7abb18def30fd59072a727f1fbf0de36df5140336081c079fff70dafb3426da26b3ba04eb56df5c8df075bc497f423c72c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
